title: CMPT-363
author:
  name: Paul Hibbitts
  email: 'paul@paulhibbitts.com'
metadata:
    description: 'CMPT-363-153 Course Companion'
taxonomies: [category,tag,month]
menu:
    - text: Stack Exchange UX
      icon: stackoverflow
      url: https://ux.stackexchange.com/
    - text: myBalsamiq
      icon: television-guide
      url: https://cmpt-363.mybalsamiq.com
github:
    enabled: true
    tree: https://github.com/paulhibbitts/cmpt-363-153-website/edit/master/user/
