title: CMPT-363
author:
  name: Paul Hibbitts
  email: 'paul@paulhibbitts.com'
metadata:
    description: 'CMPT-363-153 Course Companion'
taxonomies: [category,tag,month]
menu:
    - text: Stack Exchange UX
      url: https://ux.stackexchange.com/
    - text: myBalsamiq
      url: https://cmpt-363.mybalsamiq.com
